---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage

data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
    traefik: false

  settings.yaml: |
    title: Dudo
    description: Portal for the Home Lab

  custom.css: ""

  custom.js: ""

  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/

  services.yaml: |
    - IoT:
        - RAtGDO:
            href: http://192.168.4.135/
            description: Configuration for garage door opener
        - TuringPi
            href: https://turingpi.local/
            description: Reliable, Scalable Infrastructure for Edge & AI Apps
    - Network
        - Cloudflare:
            href: https://dash.cloudflare.com
            description: Cloudflare Dashboard
        - Unifi:
            href: https://unifi.ui.com/
            description: Unifi Site Manager

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        label: Network
        network: true
        expanded: true
    - resources:
        label: Temperature
        cputemp: true
        tempmin: 0
        tempmax: 100
        expanded: true
    - search:
        provider: google
        target: _blank

  docker.yaml: ""
