---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage

data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
    traefik: false

  settings.yaml: |
    title: Dudo
    description: Portal for the Home Lab

  custom.css: ""

  custom.js: ""

  bookmarks.yaml: |
    - Dudo:
        - GitHub:
            - href: https://github.com/dudo
              description: Developer Platform
        - Gist:
            - href: https://gist.github.com/dudo
              description: Code Snippets
        - Docker:
            - href: https://hub.docker.com/repositories/dudo
              description: Docker Hub
    - Home:
        - GitHub:
            - href: https://github.com/dudo-home-lab
              description: Home Lab GitOps
  services.yaml: |
    - IoT:
        - RAtGDO:
            href: http://garage-door.local/
            description: Configuration for garage door opener
        - TuringPi:
            href: http://turingpi.local/
            description: Reliable, Scalable Infrastructure for Edge & AI Apps
    - Network:
        - Cloudflare:
            href: https://dash.cloudflare.com/
            description: Cloudflare Dashboard
        - UniFi:
            href: https://unifi.ui.com/
            description: UniFi Site Manager

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        label: Network
        network: true
        expanded: true
    - resources:
        label: Temperature
        cputemp: true
        tempmin: 0
        tempmax: 100
        expanded: true
    - search:
        provider: google
        target: _blank

  docker.yaml: ""
