apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - config-map.yaml
  - deployment.yaml
  - http-route.yaml
  - rbac.yaml
  - service-account.yaml
  - service.yaml
images:
  - name: ghcr.io/gethomepage/homepage
    newTag: latest
    digest: sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401
configMapGenerator:
  - name: homepage-config
    literals:
      - HOMEPAGE_ALLOWED_HOSTS=www.dudo.dev
