apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - config-map.yaml
  - deployment.yaml
  - http-route.yaml
  - rbac.yaml
  - service-account.yaml
  - service.yaml
images:
  - name: ghcr.io/gethomepage/homepage
    newTag: latest
    digest: sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1
configMapGenerator:
  - name: homepage-config
    literals:
      - HOMEPAGE_ALLOWED_HOSTS=www.dudo.dev
