apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - config-map.yaml
  - deployment.yaml
  - http-route.yaml
  - rbac.yaml
  - service-account.yaml
  - service.yaml
images:
  - name: ghcr.io/gethomepage/homepage
    newTag: latest
    digest: sha256:ea801368eac6b1f0d08ad35dabcbbd0a91147a49ba9761df84b2e047532d74e5
configMapGenerator:
  - name: homepage-config
    literals:
      - HOMEPAGE_ALLOWED_HOSTS=www.dudo.dev
